<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf0c60d63a133a79794143f4019bfc57d
{
    public static $prefixLengthsPsr4 = array (
        'J' => 
        array (
            'Joohncafe\\MicroservicesCommon\\' => 30,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Joohncafe\\MicroservicesCommon\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf0c60d63a133a79794143f4019bfc57d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf0c60d63a133a79794143f4019bfc57d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf0c60d63a133a79794143f4019bfc57d::$classMap;

        }, null, ClassLoader::class);
    }
}
